version: '3.8'
services:
  cache:
    image: redis:6.2-alpine
    restart: always
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes: 
      - cache:/data
    # networks:
    #   - traefik_default
  api.miagenda.fr:
    image: ghcr.io/lemustelide/api.miagenda.fr:latest
    depends_on:
    - cache
    ports:
      - 80:80
    # labels:
    #   - traefik.enable=true
    #   - traefik.http.routers.api-miagenda-fr.rule=Host(`api.miagenda.fr`)
    #   - traefik.http.routers.api-miagenda-fr.entrypoints=websecure
    #   - traefik.http.routers.api-miagenda-fr.tls.certresolver=leresolver
    #   - traefik.http.routers.api-miagenda-fr.tls=true
    #   - traefik.http.services.api-miagenda-fr.loadbalancer.server.port=80
    # networks:
    #   - traefik_default

volumes:
  cache:
    driver: local

networks:
  traefik_default:
    external: true